language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajburt/production-docker-node-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true ajburt/production-docker-node-workflow npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "production-docker-node-workflow"
  env: "Productiondockernodeworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-506539007242"
  bucket_path: "production-docker-node-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY